// Auto-generated — do not edit manually
const clubLogoMap = {
  '1. FC Union Berlin': '/club-logos/Germany - Bundesliga/1.FC Union Berlin.png',
  '1. FSV Mainz 05': '/club-logos/Germany - Bundesliga/1.FSV Mainz 05.png',
  'AC Milan': '/club-logos/Italy - Serie A/AC Milan.png',
  'AC Sparta Praha': '/club-logos/Czech Republic - Chance Liga/AC Sparta Prague.png',
  'ACF Fiorentina': '/club-logos/Italy - Serie A/ACF Fiorentina.png',
  'AE Kifisia FC': '/club-logos/Greece - Super League 1/AE Kifisias.png',
  'AEK Athens': '/club-logos/Greece - Super League 1/AEK Athens.png',
  'AFC Bournemouth': '/club-logos/England - Premier League/AFC Bournemouth.png',
  'AJ Auxerre': '/club-logos/France - Ligue 1/AJ Auxerre.png',
  'AS Monaco': '/club-logos/France - Ligue 1/AS Monaco.png',
  'AS Roma': '/club-logos/Italy - Serie A/AS Roma.png',
  'AZ Alkmaar': '/club-logos/Netherlands - Eredivisie/AZ Alkmaar.png',
  'Aarhus GF': '/club-logos/Denmark - Superliga/Aarhus GF.png',
  'Alanyaspor': '/club-logos/Turkiye - Super Lig/Alanyaspor.png',
  'Angers SCO': '/club-logos/France - Ligue 1/Angers SCO.png',
  'Arsenal FC': '/club-logos/England - Premier League/Arsenal FC.png',
  'Aston Villa FC': '/club-logos/England - Premier League/Aston Villa.png',
  'Athletic Club': '/club-logos/Spain - LaLiga/Athletic Bilbao.png',
  'Atletico De Madrid': '/club-logos/Spain - LaLiga/Atl#U00e9tico de Madrid.png',
  'Atlético De Madrid': '/club-logos/Spain - LaLiga/Atl#U00e9tico de Madrid.png',
  'BSC Young Boys': '/club-logos/Switzerland - Super League/BSC Young Boys.png',
  'Bayer Leverkusen': '/club-logos/Germany - Bundesliga/Bayer 04 Leverkusen.png',
  'Başakşehir FK': '/club-logos/Turkiye - Super Lig/Basaksehir FK.png',
  'Beşiktaş JK': '/club-logos/Turkiye - Super Lig/Besiktas JK.png',
  'Bologna FC': '/club-logos/Italy - Serie A/Bologna FC 1909.png',
  'Borussia Dortmund': '/club-logos/Germany - Bundesliga/Borussia Dortmund.png',
  'Borussia Mönchengladbach': '/club-logos/Germany - Bundesliga/Borussia M#U00f6nchengladbach.png',
  'Brentford FC': '/club-logos/England - Premier League/Brentford FC.png',
  'Brighton & Hove Albion FC': '/club-logos/England - Premier League/Brighton & Hove Albion.png',
  'Burnley FC': '/club-logos/England - Premier League/Burnley FC.png',
  'CA Osasuna': '/club-logos/Spain - LaLiga/CA Osasuna.png',
  'CD Tondela': '/club-logos/Portugal - Liga Portugal/CD Tondela.png',
  'CF Estrela Da Amadora': '/club-logos/Portugal - Liga Portugal/CF Estrela Amadora.png',
  'Casa Pia AC': '/club-logos/Portugal - Liga Portugal/Casa Pia AC.png',
  'Celtic FC': '/club-logos/Scotland - Scottish Premiership/Celtic FC.png',
  'Cercle Brugge': '/club-logos/Belgium - Jupiler Pro League/Cercle Brugge.png',
  'Chelsea FC': '/club-logos/England - Premier League/Chelsea FC.png',
  'Club Brugge': '/club-logos/Belgium - Jupiler Pro League/Club Brugge KV.png',
  'Club Nacional': '/club-logos/Portugal - Liga Portugal/CD Nacional.png',
  'Crystal Palace FC': '/club-logos/England - Premier League/Crystal Palace.png',
  'Eintracht Frankfurt': '/club-logos/Germany - Bundesliga/Eintracht Frankfurt.png',
  'Elche CF': '/club-logos/Spain - LaLiga/Elche CF.png',
  'Everton FC': '/club-logos/England - Premier League/Everton FC.png',
  'FC Akron Tolyatti': '/club-logos/Russia - Premier Liga/Akron Togliatti.png',
  'FC Augsburg': '/club-logos/Germany - Bundesliga/FC Augsburg.png',
  'FC Barcelona': '/club-logos/Spain - LaLiga/FC Barcelona.png',
  'FC Dynamo Makhachkala': '/club-logos/Russia - Premier Liga/Dinamo Makhachkala.png',
  'FC Dynamo Moscow': '/club-logos/Russia - Premier Liga/Dynamo Moscow.png',
  'FC Hradec Králové': '/club-logos/Czech Republic - Chance Liga/FC Hradec Kralove.png',
  'FC Krasnodar': '/club-logos/Russia - Premier Liga/FC Krasnodar.png',
  'FC Lokomotiv Moscow': '/club-logos/Russia - Premier Liga/Lokomotiv Moscow.png',
  'FC Lorient': '/club-logos/France - Ligue 1/FC Lorient.png',
  'FC Lugano': '/club-logos/Switzerland - Super League/FC Lugano.png',
  'FC Midtjylland': '/club-logos/Denmark - Superliga/FC Midtjylland.png',
  'FC Nantes': '/club-logos/France - Ligue 1/FC Nantes.png',
  'FC Nordsjælland': '/club-logos/Denmark - Superliga/FC Nordsjaelland.png',
  'FC Pari Nizhny Novgorod': '/club-logos/Russia - Premier Liga/FC Pari Nizhniy Novgorod.png',
  'FC Porto': '/club-logos/Portugal - Liga Portugal/FC Porto.png',
  'FC Red Bull Salzburg': '/club-logos/Austria - Bundesliga/Red Bull Salzburg.png',
  'FC Rostov': '/club-logos/Russia - Premier Liga/FC Rostov.png',
  'FC Slovan Liberec': '/club-logos/Czech Republic - Chance Liga/FC Slovan Liberec.png',
  'FC Spartak Moscow': '/club-logos/Russia - Premier Liga/Spartak Moscow.png',
  'FC St. Gallen': '/club-logos/Switzerland - Super League/FC St. Gallen 1879.png',
  'FC St. Pauli': '/club-logos/Germany - Bundesliga/FC St. Pauli.png',
  'FC Utrecht': '/club-logos/Netherlands - Eredivisie/FC Utrecht.png',
  'FC Viktoria Plzeň': '/club-logos/Czech Republic - Chance Liga/FC Viktoria Plzen.png',
  'FC Volendam': '/club-logos/Netherlands - Eredivisie/FC Volendam.png',
  'FC Zenit St. Petersburg': '/club-logos/Russia - Premier Liga/Zenit St. Petersburg.png',
  'FCV Dender EH': '/club-logos/Belgium - Jupiler Pro League/FCV Dender EH.png',
  'FK Austria Wien': '/club-logos/Austria - Bundesliga/Austria Vienna.png',
  'Fenerbahçe SK': '/club-logos/Turkiye - Super Lig/Fenerbahce.png',
  'Feyenoord Rotterdam': '/club-logos/Netherlands - Eredivisie/Feyenoord Rotterdam.png',
  'Fulham FC': '/club-logos/England - Premier League/Fulham FC.png',
  'GNK Dinamo Zagreb': '/club-logos/Croatia - SuperSport HNL/GNK Dinamo Zagreb.png',
  'Galatasaray SK': '/club-logos/Turkiye - Super Lig/Galatasaray.png',
  'Gaziantep FK': '/club-logos/Turkiye - Super Lig/Gaziantep FK.png',
  'Genoa CFC': '/club-logos/Italy - Serie A/Genoa CFC.png',
  'Gil Vicente FC': '/club-logos/Portugal - Liga Portugal/Gil Vicente FC.png',
  'Girona FC': '/club-logos/Spain - LaLiga/Girona FC.png',
  'Grazer AK': '/club-logos/Austria - Bundesliga/Grazer AK 1902.png',
  'HNK Hajduk Split': '/club-logos/Croatia - SuperSport HNL/HNK Hajduk Split.png',
  'HNK Rijeka': '/club-logos/Croatia - SuperSport HNL/HNK Rijeka.png',
  'Hamburger SV': '/club-logos/Germany - Bundesliga/Hamburger SV.png',
  'Heart Of Midlothian FC': '/club-logos/Scotland - Scottish Premiership/Heart of Midlothian FC.png',
  'Hellas Verona FC': '/club-logos/Italy - Serie A/Hellas Verona.png',
  'Hibernian FC': '/club-logos/Scotland - Scottish Premiership/Hibernian FC.png',
  'Jagiellonia Białystok': '/club-logos/Poland - PKO BP Ekstraklasa/Jagiellonia Bialystok.png',
  'Juventus FC': '/club-logos/Italy - Serie A/Juventus FC.png',
  'KAA Gent': '/club-logos/Belgium - Jupiler Pro League/KAA Gent.png',
  'KRC Genk': '/club-logos/Belgium - Jupiler Pro League/KRC Genk.png',
  'KS Cracovia': '/club-logos/Poland - PKO BP Ekstraklasa/Cracovia.png',
  'KV Mechelen': '/club-logos/Belgium - Jupiler Pro League/KV Mechelen.png',
  'Kayserispor': '/club-logos/Turkiye - Super Lig/Kayserispor.png',
  'Kilmarnock FC': '/club-logos/Scotland - Scottish Premiership/Kilmarnock FC.png',
  'Konyaspor': '/club-logos/Turkiye - Super Lig/Konyaspor.png',
  'Le Havre AC': '/club-logos/France - Ligue 1/Le Havre AC.png',
  'Lechia Gdańsk': '/club-logos/Poland - PKO BP Ekstraklasa/Lechia Gdansk.png',
  'Leeds United FC': '/club-logos/England - Premier League/Leeds United.png',
  'Levante UD': '/club-logos/Spain - LaLiga/Levante UD.png',
  'Liverpool FC': '/club-logos/England - Premier League/Liverpool FC.png',
  'Maccabi Haifa FC': '/club-logos/Israel - Ligat ha\'Al/Maccabi Haifa.png',
  'Maccabi Tel-Aviv FC': '/club-logos/Israel - Ligat ha\'Al/Maccabi Tel Aviv.png',
  'Manchester City FC': '/club-logos/England - Premier League/Manchester City.png',
  'Manchester United FC': '/club-logos/England - Premier League/Manchester United.png',
  'Molde FK': '/club-logos/Norway - Eliteserien/Molde FK.png',
  'Motherwell FC': '/club-logos/Scotland - Scottish Premiership/Motherwell FC.png',
  'NEC Nijmegen': '/club-logos/Netherlands - Eredivisie/NEC Nijmegen.png',
  'NK Lokomotiva Zagreb': '/club-logos/Croatia - SuperSport HNL/NK Lokomotiva Zagreb.png',
  'Newcastle United FC': '/club-logos/England - Premier League/Newcastle United.png',
  'Newcastle United Jets FC': '/club-logos/England - Premier League/Newcastle United.png',
  'Nottingham Forest FC': '/club-logos/England - Premier League/Nottingham Forest.png',
  'OGC Nice': '/club-logos/France - Ligue 1/OGC Nice.png',
  'Olympique Lyonnais': '/club-logos/France - Ligue 1/Olympique Lyon.png',
  'Olympique Marseille': '/club-logos/France - Ligue 1/Olympique Marseille.png',
  'PAOK Saloniki': '/club-logos/Greece - Super League 1/PAOK Thessaloniki.png',
  'PEC Zwolle': '/club-logos/Netherlands - Eredivisie/PEC Zwolle.png',
  'PFC Ludogorets Razgrad': '/club-logos/Bulgaria - efbet Liga/Ludogorets Razgrad.png',
  'PFC Montana': '/club-logos/Bulgaria - efbet Liga/Montana.png',
  'PSV Eindhoven': '/club-logos/Netherlands - Eredivisie/PSV Eindhoven.png',
  'Pafos FC': '/club-logos/France - Ligue 1/Paris FC.png',
  'Panathinaikos FC': '/club-logos/Greece - Super League 1/Panathinaikos FC.png',
  'Paris FC': '/club-logos/France - Ligue 1/Paris FC.png',
  'Paris Saint-Germain': '/club-logos/France - Ligue 1/Paris Saint-Germain.png',
  'Pogoń Szczecin': '/club-logos/Poland - PKO BP Ekstraklasa/Pogon Szczecin.png',
  'RB Leipzig': '/club-logos/Germany - Bundesliga/RB Leipzig.png',
  'RC Celta Vigo': '/club-logos/Spain - LaLiga/Celta de Vigo.png',
  'RC Lens': '/club-logos/France - Ligue 1/RC Lens.png',
  'RC Strasbourg': '/club-logos/France - Ligue 1/RC Strasbourg Alsace.png',
  'RCD Mallorca': '/club-logos/Spain - LaLiga/RCD Mallorca.png',
  'RSC Anderlecht': '/club-logos/Belgium - Jupiler Pro League/RSC Anderlecht.png',
  'Randers FC': '/club-logos/Denmark - Superliga/Randers FC.png',
  'Rangers FC': '/club-logos/Scotland - Scottish Premiership/Rangers FC.png',
  'Rayo Vallecano': '/club-logos/Spain - LaLiga/Rayo Vallecano.png',
  'Real Madrid C. F.': '/club-logos/Spain - LaLiga/Real Madrid.png',
  'Real Madrid C.F.': '/club-logos/Spain - LaLiga/Real Madrid.png',
  'Real Oviedo': '/club-logos/Spain - LaLiga/Real Oviedo.png',
  'Real Sociedad': '/club-logos/Spain - LaLiga/Real Sociedad.png',
  'Royal Antwerp FC': '/club-logos/Belgium - Jupiler Pro League/Royal Antwerp FC.png',
  'Royale Union Saint-Gilloise': '/club-logos/Belgium - Jupiler Pro League/Union Saint-Gilloise.png',
  'SC Braga': '/club-logos/Portugal - Liga Portugal/SC Braga.png',
  'SC Freiburg': '/club-logos/Germany - Bundesliga/SC Freiburg.png',
  'SC Heracles Almelo': '/club-logos/Netherlands - Eredivisie/Heracles Almelo.png',
  'SC Telstar': '/club-logos/Netherlands - Eredivisie/SC Telstar.png',
  'SK Slavia Praha': '/club-logos/Czech Republic - Chance Liga/SK Slavia Prague.png',
  'SL Benfica': '/club-logos/Portugal - Liga Portugal/SL Benfica.png',
  'SSC Napoli': '/club-logos/Italy - Serie A/SSC Napoli.png',
  'SV Werder Bremen': '/club-logos/Germany - Bundesliga/SV Werder Bremen.png',
  'SV Zulte Waregem': '/club-logos/Belgium - Jupiler Pro League/Zulte Waregem.png',
  'Samsunspor': '/club-logos/Turkiye - Super Lig/Samsunspor.png',
  'Sarpsborg 08 FF': '/club-logos/Norway - Eliteserien/Sarpsborg 08 FF.png',
  'Servette FC': '/club-logos/Switzerland - Super League/Servette FC.png',
  'Sevilla FC': '/club-logos/Spain - LaLiga/Sevilla FC.png',
  'Silkeborg IF': '/club-logos/Denmark - Superliga/Silkeborg IF.png',
  'Sint-Truiden VV': '/club-logos/Belgium - Jupiler Pro League/Sint-Truidense VV.png',
  'Sparta Rotterdam': '/club-logos/Netherlands - Eredivisie/Sparta Rotterdam.png',
  'Sporting CP': '/club-logos/Portugal - Liga Portugal/Sporting CP.png',
  'Stade Rennais FC': '/club-logos/France - Ligue 1/Stade Rennais FC.png',
  'Standard Liege': '/club-logos/Belgium - Jupiler Pro League/Standard Li#U00e8ge.png',
  'Standard Liège': '/club-logos/Belgium - Jupiler Pro League/Standard Li#U00e8ge.png',
  'Sunderland AFC': '/club-logos/England - Premier League/Sunderland AFC.png',
  'TSG Hoffenheim': '/club-logos/Germany - Bundesliga/TSG 1899 Hoffenheim.png',
  'Torino FC': '/club-logos/Italy - Serie A/Torino FC.png',
  'Toronto FC': '/club-logos/Italy - Serie A/Torino FC.png',
  'Tottenham Hotspur FC': '/club-logos/England - Premier League/Tottenham Hotspur.png',
  'Trabzonspor': '/club-logos/Turkiye - Super Lig/Trabzonspor.png',
  'US Cremonese': '/club-logos/Italy - Serie A/US Cremonese.png',
  'US Sassuolo': '/club-logos/Italy - Serie A/US Sassuolo.png',
  'Universitatea Cluj': '/club-logos/Romania - SuperLiga/FC Universitatea Cluj.png',
  'Valencia CF': '/club-logos/Spain - LaLiga/Valencia CF.png',
  'VfB Stuttgart': '/club-logos/Germany - Bundesliga/VfB Stuttgart.png',
  'VfL Wolfsburg': '/club-logos/Germany - Bundesliga/VfL Wolfsburg.png',
  'Villarreal CF': '/club-logos/Spain - LaLiga/Villarreal CF.png',
  'West Ham United FC': '/club-logos/England - Premier League/West Ham United.png',
  'Wolfsberger AC': '/club-logos/Austria - Bundesliga/Wolfsberger AC.png',
  'Wolverhampton Wanderers FC': '/club-logos/England - Premier League/Wolverhampton Wanderers.png',
  'Çaykur Rizespor': '/club-logos/Turkiye - Super Lig/Caykur Rizespor.png',
};

export function getClubLogo(clubRaw) {
  if (!clubRaw) return null;
  const club = clubRaw.replace(/\s*\([A-Z]{2,3}\)\s*$/, '').trim();
  return clubLogoMap[club] || null;
}